### ISSUE TITLE
ach python dependency not installed by default

### ISSUE THREAD

**Issue by robEllenberg** [hubo/hubo-ach#26]
When building from source on the latest develop branch:
commit 01fca616cb4adc9a2be67440394868c6497e3869

I noticed that I couldn't import the python ach module. Based on the ach python [readme](https://github.com/golems/ach/blob/master/python/README.txt), there's a command to install the python package. Do we need to install the python bindings this way, or should this be taken care of by hubo-ach's setup?

**Comment by ndantam** [comment]
On 04/28/2013 07:39 PM, Robert Ellenberg wrote:

> When building from source on the latest develop branch:
> commit 01fca61
> https://github.com/hubo/hubo-ach/commit/01fca616cb4adc9a2be67440394868c6497e3869
> 
> I noticed that I couldn't import the python ach module. Based on the ach
> python readme
> https://github.com/golems/ach/blob/master/python/README.txt, there's a
> command to install the python package. Do we need to install the python
> bindings this way, or should this be taken care of by hubo-ach's setup?

The Autotools build for Ach does not build the Python module by default. 
  You can tell it to build and install the module with `./configure 
--with-python`.  Rationale is that AFAIK Python's distutils are 
preferred for managing Python packages over either debs or `make 
install`.  (If that's actually not the case, then we can change the 
default behavior)

See the Language Bindings/Python subsection in:
https://github.com/golems/ach/blob/master/INSTALL

-ntd

**Comment by thedancomplex** [comment]
I personally use the ach python binding all the time and would be nice to
have them in the default install.

-dan

**Comment by ndantam** [comment]
CC'ing Saul on this.  (Github needs real mailing lists)

> > Rationale is that AFAIK Python's distutils are preferred for
> > managing Python packages over either debs or `make install`.
> > 
> > On 04/28/2013 08:05 PM, thedancomplex wrote:
> > I personally use the ach python binding all the time and would be
> > nice to have them in the default install.

One issue is that the Python module requires a matching python
version on the users machine.  This would work fine for `make
install`, but would complicate deb building.  Currently, I can get
away with a single, cross-distro deb for Ach.  Pip also builds on
the end user's machine, which handles the module version issue.

-ntd

**Comment by ndantam** [comment]
Closing this issue as I believe python's distutils are preferred for managing python packages.
