### ISSUE TITLE
Update master / Debian release.

### ISSUE THREAD

**Issue by a-price** [hubo/hubo-ach#30]
The installed Debian package is now pretty far behind the develop branch. Some newer features like Hubo's joint name array are needed by hubo-motion-rt, and installing from source shouldn't be required to use these additions.

**Comment by thedancomplex** [comment]
Are you saying that the master is far behind the develop?  If so yes, I am
working on a few final fixes/additions which will be done by the 10th.

If that is not what you are talking about, what are you referring to?

-Dan

**Comment by thedancomplex** [comment]
also you can install develop via deb packages.

http://danlofaro.com/software/hubo-ach/latest-develop/

-Dan
