### ISSUE TITLE
HUBO_JMC_COUNT inconsistency

### ISSUE THREAD

**Issue by petevieira** [hubo/hubo-ach#47]
HUBO_JMC_COUNT is defined in 3 places and they are not all consistent.

The overview of the definition is:

include/hubo.h:            HUBO_JMC_COUNT = 0x36
include/hubo/canID.h:   HUBO_JMC_COUNT = 0x26
python/hubo-ach.py:     HUBO_JMC_COUNT = 0x36

Since canID.h gets included after hubo.h everywhere, I believe the definition in canID.h is correct, ie. 0x26. But this needs to be verified.

**Comment by thedancomplex** [comment]
Thank you, 0x36 is correct and NOT 0x26, in reality it should not be in
canID.  I will change in next release.

-Dan

On Mon, Oct 28, 2013 at 12:47 PM, Pete Vieira notifications@github.comwrote:

> HUBO_JMC_COUNT is defined in 3 places and they are not all consistent.
> 
> The overview of the definition is:
> 
> include/hubo.h: HUBO_JMC_COUNT = 0x36
> include/hubo/canID.h: HUBO_JMC_COUNT = 0x26
> python/hubo-ach.py: HUBO_JMC_COUNT = 0x36
> 
> Since canID.h gets included after hubo.h everywhere, I believe the
> definition in canID.h is correct, ie. 0x26. But this needs to be verified.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hubo/hubo-ach/issues/47
> .

## 

Daniel M. Lofaro Ph.D
Assistant Professor, George Mason University
Electrical and Computer Engineering Department
DARPA Robot Challenge Track-A Team DRC-Hubo Researcher
e: dan@danLofaro.com
w: http://danLofaro.com http://danlofaro.com/

**Comment by thedancomplex** [comment]
Removed duplicate def from include/hubo/canID.h (already in include/hubo.h): HUBO_JOINT_COUNT, HUBO_JMC_COUNT, HUBO_SENSOR_COUNT
